### ISSUE TITLE
sorbet/rbi/annotations/actionmailer.rbi:8: Unable to resolve constant Mail

### ISSUE THREAD

**Issue by yesthesoup** [Shopify/rbi-central#177]
### Problem

```sh
> bundle exec srb tc
sorbet/rbi/annotations/actionmailer.rbi:8: Unable to resolve constant Mail https://srb.help/5002
     8 |  sig { params(headers: T.untyped, block: T.nilable(T.proc.void)).returns(Mail::Message) }
                                                                                  ^^^^
  Did you mean Spoom::Cli::Main? Use -a to autocorrect
    sorbet/rbi/annotations/actionmailer.rbi:8: Replace with Spoom::Cli::Main
     8 |  sig { params(headers: T.untyped, block: T.nilable(T.proc.void)).returns(Mail::Message) }
                                                                                  ^^^^
    sorbet/rbi/gems/spoom@1.2.3.rbi:217: Spoom::Cli::Main defined here
     217 |class Spoom::Cli::Main < ::Thor
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Did you mean ActionMailer::Base? Use -a to autocorrect
    sorbet/rbi/annotations/actionmailer.rbi:8: Replace with ActionMailer::Base
     8 |  sig { params(headers: T.untyped, block: T.nilable(T.proc.void)).returns(Mail::Message) }
                                                                                  ^^^^
    sorbet/rbi/annotations/actionmailer.rbi:7: ActionMailer::Base defined here
     7 |class ActionMailer::Base
        ^^^^^^^^^^^^^^^^^^^^^^^^
```

### Context

Rails latest 7.0.8, fresh project, fresh install of latest sorbet/tapioca. Ran `bin/tapioca gem` to generate from installed gems.

I checked and `sorbet/rbi/annotations/actionmailer.rbi` in my project is the same as in this repo:
https://github.com/Shopify/rbi-central/blob/main/rbi/annotations/actionmailer.rbi

`sorbet/rbi/gems/actionmailer@7.0.8.rbi` is empty however - is this because it's missing in the`tapioca` repo?

![image](https://github.com/Shopify/rbi-central/assets/2483953/4c85deda-f877-42c2-b2a4-9d1631e995ac)

What should be done here? It seems like the only path is to add this constant to the `todo` - but that command is actively deprecating?

* Gem name: actionmailer / rails
* Gem version: 7.0.8
* Gem source: https://github.com/rails/rails/tree/main/actionmailer
* Gem API doc: https://api.rubyonrails.org/classes/ActionMailer/Base.html
* Tapioca version: 
* Sorbet version: 
```
> bundle list | ack '(tapioca|sorbet)'
  * sorbet (0.5.11014)
  * sorbet-runtime (0.5.11014)
  * sorbet-static (0.5.11014)
  * sorbet-static-and-runtime (0.5.11014)
  * tapioca (0.11.9)
  * yard-sorbet (0.8.1)
```

**Comment by andyw8** [comment]
:wave: Could you try with tapoica v0.11.8 to see if that makes a difference? It may be a problem with the latest release.
