### ISSUE TITLE
GraphQL::Schema#execute can return GraphQL::Query::Result

### ISSUE THREAD

**Issue by bmulholland** [Shopify/rbi-central#250]
### Problem

https://github.com/Shopify/rbi-central/blob/main/rbi/annotations/graphql.rbi#L16 is missing at least one possible return type: GraphQL::Query::Result. https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/interpreter.rb#L128

We use that in our app, for GraphQL subscriptions via ActionCable channels, ref: https://graphql-ruby.org/api-doc/1.11.5/GraphQL/Subscriptions/ActionCableSubscriptions

### Context

* Gem name: graphql
* Gem version: latest
* Gem source: linked above
* Gem API doc: https://graphql-ruby.org/api-doc/2.3.0/GraphQL/Query/Result
* Tapioca version: latest
* Sorbet version: latest

**Comment by bmulholland** [comment]
Should it just become
`sig { params(query_str: String, kwargs: T.untyped).returns(T.any(T::Hash[String, T.untyped], GraphQL::Query::Result)) }`
?

I could submit a PR for that

**Comment by bmulholland** [comment]
What's surprising about the line you linked?

**Comment by KaanOzkan** [comment]
`execute` returns `multiplex` which returns `Interpreter#run_all` which looks like it's returning an [array](https://github.com/rmosolgo/graphql-ruby/blob/b7551b54d87355fd0d451cb335425272cbfdeb05/lib/graphql/execution/interpreter.rb#L24-L34). Yard documentation matches this too.

**Comment by bmulholland** [comment]
Ah yeah -- based on that it would be confusing. Maybe you missed the next line, which takes the first element from that array?

https://github.com/rmosolgo/graphql-ruby/blob/b7551b54d87355fd0d451cb335425272cbfdeb05/lib/graphql/schema.rb#L1305

**Comment by bmulholland** [comment]
I filed an issue over at the GraphQL repo and they've actually replaced the return type to be exclusively a Result, not ever a Hash. https://github.com/rmosolgo/graphql-ruby/pull/4984

Following that, unless you see something I'm not, I'll change the type [in my PR](https://github.com/Shopify/rbi-central/pull/256) to always be a Result. Any concerns with that?

**Comment by KaanOzkan** [comment]
Thanks. Yes let's do Result.

**Comment by bmulholland** [comment]
Awesome. Updated the attached PR :)
