### ISSUE TITLE
Cleanup root directory

### ISSUE THREAD

**Issue by KaanOzkan** [Shopify/rbi-central#28]
It'd be cleaner to have a minimal root directory with things like `Gemfile`, `Gemfile.lock`, `.rubocop.yml` and `dev.yml` stored in a sub directory without hindering UX.

It's worth investing some time into it to see what are some possible options and go on from there if there's a suitable one.

**Comment by wildmaples** [comment]
Isn't having those config files in the root directory standard practice for a Ruby Gem repository? Do you have any other codebase in mind as inspiration?

**Comment by Morriar** [comment]
The thing is that this repo is not a gem, not even an application, but a collection of RBI annotations. 
The Gemfile and other files are here only for the scripts we run on CI. 

I think what @KaanOzkan is suggesting makes sense, we do not need to clutter the root directory for this.

**Comment by Morriar** [comment]
Done, I don't think we can remove much more files from the root: https://github.com/Shopify/rbi-central.
