### ISSUE TITLE
Handle gem annotations versioning

### ISSUE THREAD

**Issue by Morriar** [Shopify/rbi-central#95]
### Problem

Available constants, methods and signatures may vary depending on the version of the gem.

* [x] `rbi-central` should provide a way to annotates specific versions of a gem
* [x] `tapioca` should pull only relevant annotations for the considered version of a gem

# Possible solution

Annotate the annotations with the gem version concerned when _we need_ to make a distinction between two versions:

```ruby
module Foo
  # This annotation is defined in all versions
  def foo; end

  # This annotation is only available in versions > 1.0
  # @version > 1.0
  def bar(x); end

  # This annotation is only available in versions <= 1.0
  # @version <= 1.0
  def bar; end
end
```

**Comment by KaanOzkan** [comment]
A comment above method/constant definitions with the format `# @version > x.y.z` can be used to specify versions. `tapioca annotations` command will only pick applicable definitions.
